# Лабораторная работа №5
## Выполнила студентка группы ДПИ22-2, Сирина Яна

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, mean_squared_error, r2_score, explained_variance_score, max_error, mean_absolute_error
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.datasets import load_iris, make_regression
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('heart.csv')
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [3]:
y = data["output"]
x = data.drop("output", axis=1)

logistic = LogisticRegression(max_iter=1000).fit(x, y)
logistic.score(x, y)

0.8481848184818482

In [4]:
x_train, y_train = x[:200], y[:200]
x_train.shape, y_train.shape
x_test, y_test = x[200:], y[200:]
x_test.shape, y_test.shape

((103, 13), (103,))

In [5]:
logistic_test = LogisticRegression(max_iter=1000).fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)
N = int(x.shape[0] * 0.8)

x_train, y_train, x_test, y_test = x[:N], y[:N], x[N:], y[N:]
x_train.shape, y_train.shape, x_test.shape, y_test.shape

/Users/yanasirina/Desktop/PycharmProjects/ml_labs/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


((242, 13), (242,), (61, 13), (61,))

In [6]:
logistic_test = LogisticRegression(max_iter=1000).fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

(0.8925619834710744, 0.6229508196721312)

In [7]:
data.tail()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0

In [8]:
from numpy.random import shuffle
mask = np.array([True] * N + [False] * (y.shape[0] - N))
shuffle(mask)
mask

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True, False,  True, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
       False, False,

In [9]:
x_train = x[mask]
x_train.shape
x_train, y_train, x_test, y_test = x[mask], y[mask], x[~mask], y[~mask]
x_train.shape, y_train.shape, x_test.shape, y_test.shape
logistic_test = LogisticRegression(max_iter=1000).fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

(0.8471074380165289, 0.8852459016393442)

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [11]:
y_test_pred = logistic_test.predict(x_test)
y_train_pred = logistic_test.predict(x_train)
confusion_matrix(y_train, y_train_pred)

array([[ 80,  24],
       [ 12, 126]])

In [12]:
confusion_matrix(y_test, y_test_pred)

array([[29,  5],
       [ 3, 24]])

In [13]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.91      0.85      0.88        34
           1       0.83      0.89      0.86        27

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61



In [14]:
precision_score(y_test, y_test_pred)

0.8275862068965517

In [15]:
metrics = pd.DataFrame({
    "Train": [
        accuracy_score(y_train, y_train_pred),
        precision_score(y_train, y_train_pred),
        recall_score(y_train, y_train_pred),
        f1_score(y_train, y_train_pred),
    ],
    "Test": [
        accuracy_score(y_test, y_test_pred),
        precision_score(y_test, y_test_pred),
        recall_score(y_test, y_test_pred),
        f1_score(y_test, y_test_pred),
    ],
}, index = ["Accuracy", "Precision", "Recall", "F1"])

metrics

Train      Test
Accuracy   0.851240  0.868852
Precision  0.840000  0.827586
Recall     0.913043  0.888889
F1         0.875000  0.857143

# 1. Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке.

In [16]:
classification_models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

results_task1 = []
for name, model in classification_models.items():
    X_train, X_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results_task1.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred)
    })

pd.DataFrame(results_task1)

Model  Accuracy  Precision   Recall        F1
0  Logistic Regression  0.885246   0.878788  0.90625  0.892308
1        Random Forest  0.836066   0.843750  0.84375  0.843750
2                  SVM  0.704918   0.666667  0.87500  0.756757
3                  KNN  0.688525   0.685714  0.75000  0.716418
4          Naive Bayes  0.868852   0.900000  0.84375  0.870968
5        Decision Tree  0.754098   0.840000  0.65625  0.736842
6    Gradient Boosting  0.770492   0.800000  0.75000  0.774194

# 2. Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [17]:
iris = load_iris()
X_iris, y_iris = iris.data, iris.target
iris_models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

results_task2 = []
for name, model in iris_models.items():
    X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(X_iris, y_iris, train_size=0.8, random_state=42)
    model.fit(X_train_iris, y_train_iris)
    y_pred_iris = model.predict(X_test_iris)
    results_task2.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test_iris, y_pred_iris),
        "Precision": precision_score(y_test_iris, y_pred_iris, average='weighted'),
        "Recall": recall_score(y_test_iris, y_pred_iris, average='weighted'),
        "F1": f1_score(y_test_iris, y_pred_iris, average='weighted')
    })

pd.DataFrame(results_task2)

Model  Accuracy  Precision  Recall   F1
0      Decision Tree       1.0        1.0     1.0  1.0
1      Random Forest       1.0        1.0     1.0  1.0
2  Gradient Boosting       1.0        1.0     1.0  1.0

# 3.Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.

In [18]:
# 3. Анализ для задачи регрессии с 5-10 различными моделями
X_reg, y_reg = make_regression(n_samples=200, n_features=5, noise=0.1, random_state=42)
regression_models = {
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "Ridge": Ridge(),
    "Lasso": Lasso()
}

results_task3 = []
for name, model in regression_models.items():
    X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, train_size=0.8, random_state=42)
    model.fit(X_train_reg, y_train_reg)
    y_pred_reg = model.predict(X_test_reg)
    results_task3.append({
        "Model": name,
        "Explained Variance": explained_variance_score(y_test_reg, y_pred_reg),
        "Max Error": max_error(y_test_reg, y_pred_reg),
        "Mean Absolute Error": mean_absolute_error(y_test_reg, y_pred_reg),
        "Mean Squared Error": mean_squared_error(y_test_reg, y_pred_reg),
        "R2 Score": r2_score(y_test_reg, y_pred_reg)
    })

results_task3_df = pd.DataFrame(results_task3)
print("\nTask 3: Analysis with regression dataset")
print(results_task3_df)
results_task3_df



Task 3: Analysis with regression dataset
               Model  Explained Variance  Max Error  Mean Absolute Error  \
0      Decision Tree            0.841258  91.613698            31.921641   
1      Random Forest            0.901919  89.230458            20.867051   
2  Gradient Boosting            0.933919  56.108319            18.730626   
3              Ridge            0.999958   1.495069             0.514335   
4              Lasso            0.999554   5.876628             1.627507   

   Mean Squared Error  R2 Score  
0         1418.481524  0.837898  
1          863.013642  0.901376  
2          583.758494  0.933289  
3            0.390410  0.999955  
4            4.096165  0.999532  


Model  Explained Variance  Max Error  Mean Absolute Error  \
0      Decision Tree            0.841258  91.613698            31.921641   
1      Random Forest            0.901919  89.230458            20.867051   
2  Gradient Boosting            0.933919  56.108319            18.730626   
3              Ridge            0.999958   1.495069             0.514335   
4              Lasso            0.999554   5.876628             1.627507   

   Mean Squared Error  R2 Score  
0         1418.481524  0.837898  
1          863.013642  0.901376  
2          583.758494  0.933289  
3            0.390410  0.999955  
4            4.096165  0.999532